---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jpto-dev-cert-staging
  namespace: default
spec:
  secretName: jpto-dev-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: jpto.dev
  dnsNames:
  - jpto.dev