---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jpto-dev-cert-staging
  namespace: jpto-dev
spec:
  secretName: jpto-dev-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: www.jpto.dev
  dnsNames:
  - www.jpto.dev