---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jpto-dev-cert-production
  namespace: jpto-dev
spec:
  secretName: jpto-dev-tls-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: www.jpto.dev
  dnsNames:
  - www.jpto.dev